ShoppingCard2FE/Controllers/AuthenticationController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using NuGet.Common;
using NuGet.Packaging.Signing;
using ShoppingCartModels.ModelDto;
using ShoppingCartModels.ResponseModel;
using System.IdentityModel.Tokens.Jwt;
using System.Net.Http.Headers;
using System.Security.Claims;
using System.Text;

namespace ShoppingCard2FE.Controllers
{
    public class AuthenticationController : Controller
    {

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public async Task<ActionResult> Index(SignUpModel model)
        {
            if (ModelState.IsValid)
            {

                SignUpModel t = new SignUpModel();
                using (var httpClient = new HttpClient())
                {
                    StringContent content = new StringContent(JsonConvert.SerializeObject(model), Encoding.UTF8, "application/json");

                    using (var response = await httpClient.PostAsync("https://localhost:7226/api/Authenticate/SignUp", content))
                    {
                        string apiResponse = await response.Content.ReadAsStringAsync();
                        t = JsonConvert.DeserializeObject<SignUpModel>(apiResponse);
                    }
                }
                return RedirectToAction("Login");

            }
            ModelState.AddModelError("Model", "There is already one like that");
            return View();
        }

        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginModel model)
        {
            if (ModelState.IsValid)
            {
                var loginResponse = new LoginResponse();
                using (var httpClient = new HttpClient())
                {
                    StringContent content = new StringContent(JsonConvert.SerializeObject(model), Encoding.UTF8, "application/json");

                    using (var response = await httpClient.PostAsync("https://localhost:7226/api/Authenticate/Login", content))
                    {
                        if (response.IsSuccessStatusCode)
                        {
                            string apiResponse = await response.Content.ReadAsStringAsync();
                            loginResponse = JsonConvert.DeserializeObject<LoginResponse>(apiResponse);

                            HttpContext.Session.SetString("Role", loginResponse.Role);
                            HttpContext.Session.SetString("UserName", loginResponse.UserName);
                            HttpContext.Session.SetString("Token", loginResponse.Token);
                            var jwt = new JwtSecurityTokenHandler().ReadJwtToken(loginResponse.Token);

                            var claimsIdentity = new ClaimsIdentity(jwt.Claims, CookieAuthenticationDefaults.AuthenticationScheme);
                            HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme,
                            new ClaimsPrincipal(claimsIdentity));

                            if (loginResponse.Role == "Admin")
                            {

                            return RedirectToAction("DisplayProducts","Admin");
                            }
                            else
                            {
                            return RedirectToAction("DisplayProducts","User");

                            }
                        }
                        else
                        {
                            ModelState.AddModelError(string.Empty, "Invalid login attempt. Please try again.");
                        }
                    }
                }
            }
            return View(model);
        }
        [HttpGet]
        public async Task< ActionResult> Logout()
        {
            HttpContext.Session.Clear();
            await HttpContext.SignOutAsync();
            return RedirectToAction("Login");
        }

    }
}

ShoppingCard2FE/Controllers/PostController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.DotNet.MSIdentity.Shared;
using Microsoft.Extensions.Hosting;
using Newtonsoft.Json;
using ShoppingCard2FE.Models.EntityModels;
using ShoppingCard2FE.Models.ModelDto;
using ShoppingCartModels.EntityModels;
using System.Net.Http;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Text;

namespace ShoppingCard2FE.Controllers
{
    //[Authorize(Roles ="Admin")]
    public class PostController : Controller
    {
        private readonly IWebHostEnvironment _hostEnvironment;
    
        public PostController(IWebHostEnvironment hostEnvironment)
        {
            _hostEnvironment = hostEnvironment;
        }

        [HttpGet]

        public IActionResult PostOne()
        {
            ImageDTo imageDTo = new ImageDTo();
            return View(imageDTo);
        }

        [HttpPost]
        public async Task<IActionResult> PostOne(ImageDTo imageDto)
        {
            string wwwRootPath = _hostEnvironment.WebRootPath;
            string fileName = Path.GetFileNameWithoutExtension(imageDto.ImageFile.FileName);
            string extension = Path.GetExtension(imageDto.ImageFile.FileName);
            imageDto.ImageName=  fileName + DateTime.Now.ToString("yymmssfff") + extension;
            string path = Path.Combine(wwwRootPath + "/Images/", imageDto.ImageName);
            PostDto postDto = new PostDto
            {
                PostTitle= imageDto.Title,
                PostImage=imageDto.ImageName
            };
            using (var fileStream = new FileStream(path, FileMode.Create))
            {
                await imageDto.ImageFile.CopyToAsync(fileStream);
            }
            string token = HttpContext.Session.GetString("Token");
            HttpClient client = new HttpClient();
            client.DefaultRequestHeaders.Add("Authorization", "Bearer " + token);
            StringContent content = new StringContent(JsonConvert.SerializeObject(postDto), Encoding.UTF8, "application/json");

            using (var response = await client.PostAsync("https://localhost:7226/api/Product/addNewPost", content))
            {
                if (response.IsSuccessStatusCode)
                {
                    return Redirect("GetImages");
                }
            }
            return View(imageDto);
        
        }

        [HttpGet]

        public async Task<IActionResult> GetImages()
        {
            List<PostDto> postDtos = new List<PostDto>();
            string token = HttpContext.Session.GetString("Token");
            
            var client = new HttpClient();
            client.DefaultRequestHeaders.Add("Authorization", "Bearer " + token);

            using( var response = await client.GetAsync("https://localhost:7226/api/Product/GetAllImage"))
            {
                if (response.IsSuccessStatusCode)
                {
                    string jsonResponse = await response.Content.ReadAsStringAsync();
                    postDtos = JsonConvert.DeserializeObject<List<PostDto>>(jsonResponse);

                    return View(postDtos);
                }
            }
            return View();
        }

    
    }
}

ShoppingCard2FE/Views/Admin/AddProduct.cshtml
@model ShoppingCartModels.ModelDto.ProductDto
@{
    ViewBag.Title = "AddProduct";
}

<h2>Add Product</h2>
@using (Html.BeginForm("AddProduct", "Admin", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })


        <div class="form-group">
            @Html.LabelFor(model => model.ProductName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProductName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProductName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProductPrice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProductPrice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProductPrice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProductDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProductDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProductDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProductQuantity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProductQuantity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProductQuantity, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.ProductCatagory, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProductCatagory, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProductCatagory, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group mt-2">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Add New Product" class="btn btn-success" />
            </div>
        </div>
    </div>
}


<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ShoppingCard2FE/Views/Admin/DeleteProduct.cshtml
@model ShoppingCartModels.EntityModels.Product

@{
    ViewData["Title"] = "DeleteProduct";
}

<h1>DeleteProduct</h1>
-
<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Product</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProductName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProductName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProductDescription)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProductDescription)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProductQuantity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProductQuantity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProductPrice)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProductPrice)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProductCatagory)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProductCatagory)
        </dd>
    </dl>
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
    @Html.Hidden("id", Model.Id)
        <a asp-action="DisplayProducts">Back to List</a>
    </form>
</div>

ShoppingCard2FE/Views/Admin/DisplayProducts.cshtml
@model List<ShoppingCartModels.EntityModels.Product>

@{
    ViewData["Title"] = "DisplayProducts";
}

<div class="d-flex justify-content-between">
@*    <h2>Hi, @Session["userName"]</h2>*@
    @Html.ActionLink("Logout", "Logout", "Authentication", "", new { @class = "btn btn btn-outline-danger" })
</div>

<p>
    @Html.ActionLink("Add New Product", "AddProduct", "Admin", new { @class = "btn btn btn-primary" })
</p>
<p>
    @Html.ActionLink("Add New Post", "PostOne", "Post", new { @class = "btn btn btn-primary" })
</p>
<table class="table">
    <thead>
        <tr>
            <th>Product Name</th>
            <th>Description</th>
            <th>Quantity</th>
            <th>Price</th>
            <th>Category</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var product in Model)
        {
            <tr>
                <td>@product.ProductName</td>
                <td>@product.ProductDescription</td>
                <td>@product.ProductQuantity</td>
                <td>@product.ProductPrice</td>
                <td>@product.ProductCatagory</td>
                <td>
                    <a asp-action="Edit" asp-route-id="@product.Id">Edit</a> |
                    <a asp-action="DeleteProduct" asp-route-id="@product.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

<div>
    <a asp-action="Index">Back to List</a>
</div>

ShoppingCard2FE/Views/Admin/Edit.cshtml
@model ShoppingCartModels.EntityModels.Product

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>ProductDto</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ProductName" class="control-label"></label>
                <input asp-for="ProductName" class="form-control" />
                <span asp-validation-for="ProductName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProductDescription" class="control-label"></label>
                <input asp-for="ProductDescription" class="form-control" />
                <span asp-validation-for="ProductDescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProductQuantity" class="control-label"></label>
                <input asp-for="ProductQuantity" class="form-control" />
                <span asp-validation-for="ProductQuantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProductPrice" class="control-label"></label>
                <input asp-for="ProductPrice" class="form-control" />
                <span asp-validation-for="ProductPrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProductCatagory" class="control-label"></label>
                <input asp-for="ProductCatagory" class="form-control" />
                <span asp-validation-for="ProductCatagory" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}